name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "$EC2_KEY" > TESTrepo.pem
          chmod 600 TESTrepo.pem

      - name: Deploy to EC2
        run: |
          scp -i TESTrepo.pem -o StrictHostKeyChecking=no -r ./build/* ubuntu@34.204.74.178:/home/ubuntu/AWS/
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
