name: Deploy to EC2

on:
  push:
    branches:
      - master  # Or main, depending on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Store your private key in GitHub Secrets

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Or whichever version you're using

      - name: Install dependencies
        run: npm install
        working-directory: ./AWS  # Path to your React app

      - name: Build React app
        run: npm run build
        working-directory: ./AWS  # Path to your React app

      - name: Deploy to EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./AWS/build/* ubuntu@your-ec2-public-ip:/home/ubuntu/AWS/build/
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@your-ec2-public-ip 'bash -s' < ./deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
